# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Question.create(text: "TSA guidelines now prohibit __________ on airplanes.")
Question.create(text: "It's a pity that kids these days are all getting involved with __________.")
Question.create(text: "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.")
Question.create(text: "Major League Baseball has banned __________ for giving players an unfair advantage.")
Question.create(text: "What is Batman's guilty pleasure?")
Question.create(text: "Next from J.K. Rowling: Harry Potter and the Chamber of __________.")
Question.create(text: "I'm sorry, Professor, but I couldn't complete my homework because of __________.")
Question.create(text: "What did I bring back from Mexico?")
Question.create(text: "__________? There's an app for that.")
Question.create(text: "__________. Betcha can't have just one!")
Question.create(text: "What's my anti-drug?")
Question.create(text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.")
Question.create(text: "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time. ")
Question.create(text: "What's my secret power?")
Question.create(text: "What's the new fad diet?")
Question.create(text: "What did Vin Diesel eat for dinner?")
Question.create(text: "When Pharaoh remained unmoved, Moses called down a Plague of __________.")
Question.create(text: "How am I maintaining my relationship status?")
Question.create(text: "What's the crustiest?")
Question.create(text: "In L.A. County Jail, word is you can trade 200 cigarettes for __________.")
Question.create(text: "After the earthquake, Sean Penn brought __________ to the people of Haiti.")
Question.create(text: "Instead of coal, Santa now gives the bad children __________.")
Question.create(text: "Life for American Indians was forever changed when the White Man introduced them to __________.")
Question.create(text: "What's Teach for America using to inspire inner city students to succeed?")
Question.create(text: "Maybe she's born with it. Maybe it's __________.")
Question.create(text: "In Michael Jackson's final moments, he thought about __________.")
Question.create(text: "White people like __________.")
Question.create(text: "Why do I hurt all over?")
Question.create(text: "A romantic, candlelit dinner would be incomplete without __________.")
Question.create(text: "What will I bring back in time to convince people that I am a powerful wizard?")
Question.create(text: "BILLY MAYS HERE FOR __________.")
Question.create(text: "The class field trip was completely ruined by __________.")
Question.create(text: "What's a girl's best friend?")
Question.create(text: "Dear Abby, I'm having some trouble with __________ and would like your advice.")
Question.create(text: "When I am President of the United States, I will create the Department of __________.")
Question.create(text: "What are my parents hiding from me?")
Question.create(text: "What never fails to liven up the party?")
Question.create(text: "What gets better with age?")
Question.create(text: "__________: Good to the last drop.")
Question.create(text: "I got 99 problems but __________ ain't one.")
Question.create(text: "__________. It's a trap!")
Question.create(text: "MTV's new reality show features eight washed-up celebrities living with __________.")
Question.create(text: "What would grandma find disturbing, yet oddly charming?")
Question.create(text: "What's the most emo?")
Question.create(text: "During sex, I like to think about __________.")
Question.create(text: "What ended my last relationship?")
Question.create(text: "What's that sound?")
Question.create(text: "__________. That's how I want to die.")
Question.create(text: "Why am I sticky?")
Question.create(text: "What's the next Happy Meal toy?")
Question.create(text: "What's there a ton of in heaven?")
Question.create(text: "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.")
Question.create(text: "What will always get you laid?")
Question.create(text: "__________: Kid-tested, mother-approved.")
Question.create(text: "Why can't I sleep at night?")
Question.create(text: "What's that smell?")
Question.create(text: "What helps Obama unwind?")
Question.create(text: "This is the way the world ends / This is the way the world ends / Not with a bang but with __________.")
Question.create(text: "Coming to Broadway this season, __________: The Musical.")
Question.create(text: "Anthropologists have recently discovered a primitive tribe that worships __________.")
Question.create(text: "But before I kill you, Mr. Bond, I must show you __________.")
Question.create(text: "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.")
Question.create(text: "Next on ESPN2: The World Series of __________.")
Question.create(text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.")
Question.create(text: "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.")
Question.create(text: "War! What is it good for?")
Question.create(text: "What gives me uncontrollable gas?")
Question.create(text: "What do old people smell like?")
Question.create(text: "What am I giving up for Lent?")
Question.create(text: "Alternative medicine is now embracing the curative powers of __________.")
Question.create(text: "What did the US airdrop to the children of Afghanistan?")
Question.create(text: "What does Dick Cheney prefer?")
Question.create(text: "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.")
Question.create(text: "What don't you want to find in your Chinese food?")
Question.create(text: "I drink to forget __________.")
Question.create(text: "__________. High five, bro.")
Question.create(text: "He who controls __________ controls the world.")
Question.create(text: "The CIA now interrogates enemy agents by repeatedly subjecting them to __________.")
Question.create(text: "In Rome, there are whisperings that the Vatican has a secret room devoted to __________.")
Question.create(text: "Science will never explain the origin of __________.")
Question.create(text: "When all else fails, I can always masturbate to __________.")
Question.create(text: "I learned the hard way that you can't cheer up a grieving friend with __________.")
Question.create(text: "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated __________.")
Question.create(text: "The socialist governments of Scandinavia have declared that access to __________ is a basic human right.")
Question.create(text: "In his new self-produced album, Kanye West raps over the sounds of __________.")
Question.create(text: "What's the gift that keeps on giving?")
Question.create(text: "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only __________ and his wits. ")
Question.create(text: "When I pooped, what came out of my butt?")
Question.create(text: "In the distant future, historians will agree that __________ marked the beginning of America's decline.")
Question.create(text: "What has been making life difficult at the nudist colony?")
Question.create(text: "And I would have gotten away with it, too, if it hadn't been for __________.")
Question.create(text: "What brought the orgy to a grinding halt?")
Question.create(text: "__________. High five, bro.")
Question.create(text: "TSA guidelines now prohibit __________ on airplanes.")
Question.create(text: "It's a pity that kids these days are all getting involved with __________.")
Question.create(text: "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.")
Question.create(text: "Major League Baseball has banned __________ for giving players an unfair advantage.")
Question.create(text: "What is Batman's guilty pleasure?")
Question.create(text: "Next from J.K. Rowling: Harry Potter and the Chamber of __________.")
Question.create(text: "I'm sorry, Professor, but I couldn't complete my homework because of __________.")
Question.create(text: "What did I bring back from Mexico?")
Question.create(text: "__________? There's an app for that.")
Question.create(text: "Betcha can't have just one!")
Question.create(text: "What's my anti-drug?")
Question.create(text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.")
Question.create(text: "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time.")
Question.create(text: "What's my secret power?")
Question.create(text: "What's the new fad diet?")
Question.create(text: "What did Vin Diesel eat for dinner?")
Question.create(text: "When Pharaoh remained unmoved, Moses called down a Plague of __________.")
Question.create(text: "How am I maintaining my relationship status?")
Question.create(text: "What's the crustiest?")
Question.create(text: "When I'm in prison, I'll have __________ smuggled in.")
Question.create(text: "After Hurricane Katrina, Sean Penn brought __________ to the people of New Orleans.")
Question.create(text: "Instead of coal, Santa now gives the bad children __________.")
Question.create(text: "Life was difficult for cavemen before __________.")
Question.create(text: "What's Teach for America using to inspire inner city students to succeed?")
Question.create(text: "Who stole the cookies from the cookie jar?")
Question.create(text: "In Michael Jackson's final moments, he thought about __________.")
Question.create(text: "White people like __________.")
Question.create(text: "Why do I hurt all over?")
Question.create(text: "A romantic candlelit dinner would be incomplete without __________.")
Question.create(text: "What will I bring back in time to convince people that I am a powerful wizard?")
Question.create(text: "BILLY MAYS HERE FOR __________.")
Question.create(text: "The class field trip was completely ruined by __________.")
Question.create(text: "What's a girl's best friend?")
Question.create(text: "I wish I hadn't lost the instruction manual for __________.")
Question.create(text: "When I am President of the United States, I will create the Department of __________.")
Question.create(text: "What are my parents hiding from me?")
Question.create(text: "What never fails to liven up the party?")
Question.create(text: "What gets better with age?")
Question.create(text: "__________: good to the last drop.")
Question.create(text: "I got 99 problems but __________ ain't one.")
Question.create(text: "It's a trap!")
Question.create(text: "MTV's new reality show features eight washed-up celebrities living with __________.")
Question.create(text: "What would grandma find disturbing, yet oddly charming?")
Question.create(text: "What's the most emo?")
Question.create(text: "During sex, I like to think about __________.")
Question.create(text: "What ended my last relationship?")
Question.create(text: "What's that sound?")
Question.create(text: "__________. That's how I want to die.")
Question.create(text: "Why am I sticky?")
Question.create(text: "What's the next Happy Meal® toy?")
Question.create(text: "What's there a ton of in heaven?")
Question.create(text: "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.")
Question.create(text: "What will always get you laid?")
Question.create(text: "__________: kid tested, mother approved.")
Question.create(text: "Why can't I sleep at night?")
Question.create(text: "What's that smell?")
Question.create(text: "What helps Obama unwind?")
Question.create(text: "This is the way the world ends \ This is the way the world ends \ Not with a bang but with __________.")
Question.create(text: "Coming to Broadway this season, __________: The Musical.")
Question.create(text: "Anthropologists have recently discovered a primitive tribe that worships __________.")
Question.create(text: "But before I kill you, Mr. Bond, I must show you __________.")
Question.create(text: "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.")
Question.create(text: "Due to a PR fiasco, Walmart no longer offers __________.")
Question.create(text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.")
Question.create(text: "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.")
Question.create(text: "War! What is it good for?")
Question.create(text: "What gives me uncontrollable gas?")
Question.create(text: "What do old people smell like?")
Question.create(text: "Sorry everyone, I just __________.")
Question.create(text: "Alternative medicine is now embracing the curative powers of __________.")
Question.create(text: "The U.S. has begun airdropping __________ to the children of Afghanistan.")
Question.create(text: "What does Dick Cheney prefer?")
Question.create(text: "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.")
Question.create(text: "What don't you want to find in your Chinese food?")
Question.create(text: "I drink to forget __________.")
